[versions]
th2 = "0.3.14"

[libraries]
th2-grpc-common = { group = "com.exactpro.th2", name = "grpc-common", version = "4.7.5" }

[plugins]
th2-publish = { id = "com.exactpro.th2.gradle.publish", version.ref = "th2" }
th2-grpc = { id = "com.exactpro.th2.gradle.grpc", version.ref = "th2" }